version: "3"
services: 
  frontend:
    image: nodeapp
    ports:
      - 3000:3000
    command: npm start
    container_name: frontend

  backend:
    container_name: backend
    ports:
      - 80:3000
    image: nodeapp
    command: node index.js
