name: Practise

run-name: ${{github.actor}} iniating workflow.

on:
  push:
    branches:
    - main

  workflow_dispatch:

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - name: checking out
        uses: actions/checkout@v4.1.1

      - name: setting up node js
        uses: actions/setup-node@v4.0.1
        with:
          node-version: 20
          
      - name: installing dependencies
        run: npm install

      - name: build app
        run: npm run build-react

      - name: rsync deployments
        uses: burnett01/rsync-deployments@6.0.0
        with:
          switches: -avzr --delete
          path: src/
          remote_path: /home/ubuntu
          remote_host: 34.201.250.223
          remote_user: ubuntu
          remote_key: ${{ secrets.DEPLOY_KEY }}
      
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.1
        with:
          host: 34.201.250.223
          username: ubuntu
          key: ${{ secrets.DEPLOY_KEY }}
          port: 22
          script: |
            docker build -t nodeapp .
            docker compose down
            docker compose up
